import os
from dotenv import load_dotenv

load_dotenv()

JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
HIGHLIGHT_PROJECT_ID = os.getenv("HIGHLIGHT_PROJECT_ID")
ANALYTICS_API_KEY = os.getenv("ANALYTICS_API_KEY")
TURNSTILE_SECRET_KEY = os.getenv("TURNSTILE_SECRET_KEY")
VERDICTS_DISCORD_WEBHOOK_URL = os.getenv("VERDICTS_DISCORD_WEBHOOK_URL")
REPORTS_DISCORD_WEBHOOK_URL = os.getenv("REPORTS_DISCORD_WEBHOOK_URL")
DB_CONNECTION_STRING = os.getenv("DB_CONNECTION_STRING")
MASTER_USER = os.getenv("MASTER_USER")
MASTER_PASSWORD = os.getenv("MASTER_PASSWORD")
